name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
tag-prefix: "v"

categories:
  - title: ":lock: Security Issues"
    labels: [security]

  - title: ":rocket: Updates"
    labels: [enhancement, feature, update]

  - title: ":bug: Bug Fixes"
    labels: [bug, bugfix, fix]

  - title: ":memo: Documentation"
    labels: [documentation, docs]

  - title: ":construction: Work in Progress"
    labels: [wip, in-progress, incomplete, partial, hotfix]

  - title: ":package: Dependencies"
    labels: [dependencies, dependency]

  - title: ":test_tube: Tests and Refactor"
    labels: [refactoring, refactor, tests, testing]

  - title: ":robot: CI/CD and Pipelines"
    labels: [build, ci, pipeline]

change-template: "- $TITLE — @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels: [major]
  minor:
    labels: [minor, feature, update, enhancement]
  default: patch

exclude-labels: [skip-changelog]

template: |
  ## Here's What Changed

  $CHANGES

  ---

footer: |
  Current Release: [v$RESOLVED_VERSION](../../releases/tag/v$RESOLVED_VERSION)
  Previous Release: [$PREVIOUS_TAG](../../releases/tag/$PREVIOUS_TAG)

  [Detailed comparison](../../compare/$PREVIOUS_TAG...v$RESOLVED_VERSION)
