# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

builds:
  - id: dummy
    skip: true


dockers_v2:
  - id: standard
    images:
      - "ghcr.io/mpapenbr/{{ .ProjectName }}"

    labels:
      org.opencontainers.image.created: "{{ .Date }}"
      org.opencontainers.image.title: "{{ .ProjectName }}"
      org.opencontainers.image.revision: "{{ .FullCommit }}"
      org.opencontainers.image.version: "{{ .Version }}"
      org.opencontainers.image.source: "https://{{ .ModulePath }}"
      org.opencontainers.image.url: "https://{{ .ModulePath }}"

      org.opencontainers.image.description: "Frontend for iRacelog"
      org.opencontainers.image.licenses: "MIT License"
      description: "Frontend for iRacelog"
      maintainer: "mpapenbr"
    annotations:
      "index:org.opencontainers.image.description": "Frontend for iRacelog"
    platforms:
      - linux/amd64
      - linux/arm64
    sbom: true
    dockerfile: Dockerfile.nginx
    extra_files:
      - docker/my-default.conf
      - docker/dist

sboms:
  - artifacts: archive

checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ incpatch .Version }}-next"
  
release:
  prerelease: auto
  footer: |
    ---
    _Released with [GoReleaser](https://goreleaser.com)!_
