minimumReleaseAgeExclude:
  - '@buf/mpapenbr_iracelog.bufbuild_es'
  # remove the following if dependabot cooldown is active
  - '@connectrpc/connect-web@2.1.2'
  - '@connectrpc/connect@2.1.2'
  - antd@6.4.4
