name: Node.JS CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Install pnpm
        uses: pnpm/action-setup@f520eceda224fe1a4aed5a2a27a194379a409996 # v6
      - name: Use Node.js 24
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: "24"
          cache: "pnpm"
      - name: Prep npm for using packages from buf.build
        run: |
          pnpm config set @buf:registry  https://buf.build/gen/npm/v1/

      - name: Print pnpm version
        run: pnpm --version
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Test
        run: pnpm test:no-watch --passWithNoTests
        env:
          CI: true
          RUN_SLOW_TESTS: true
#      - name: Build
#        run: yarn build
