name: Node.JS CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js 20
        uses: actions/setup-node@v6
        with:
          node-version: "20"
          cache: "pnpm"
      - name: Prep npm for using packages from buf.build
        run: |
          pnpm config set @buf:registry  https://buf.build/gen/npm/v1/

      - name: Install dependencies
        run: pnpm install
      - name: Test
        run: pnpm test:no-watch --passWithNoTests
        env:
          CI: true
          RUN_SLOW_TESTS: true
#      - name: Build
#        run: yarn build
