name: Node.JS CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"
      - name: Prep npm for using packages from github
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc
          echo "@${{ github.repository_owner }}:registry=https://npm.pkg.github.com/" >> ~/.npmrc
          pnpm config set @buf:registry  https://buf.build/gen/npm/v1/

      - name: Install dependencies
        run: pnpm install
      - name: Test
        run: pnpm test:no-watch --passWithNoTests
        env:
          CI: true
          RUN_SLOW_TESTS: true
#      - name: Build
#        run: yarn build
