name: Build release
on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prep
        id: prep
        run: |
          GHCR_IMAGE=ghcr.io/${{ github.repository_owner }}/iracelog-web
          VERSION=edge
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          elif [[ $GITHUB_REF == refs/heads/* ]]; then
            VERSION=$(echo ${GITHUB_REF#refs/heads/} | sed -r 's#/+#-#g')
          elif [[ $GITHUB_REF == refs/pull/* ]]; then
            VERSION=pr-${{ github.event.number }}
          fi
          TAGS="${GHCR_IMAGE}:${VERSION}"
          if [ "${{ github.event_name }}" = "push" ]; then
            TAGS="$TAGS,${GHCR_IMAGE}:sha-${GITHUB_SHA::8}"
          fi
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "tags=${TAGS}" >> $GITHUB_OUTPUT
          echo "ghcr_image=${GHCR_IMAGE}" >> $GITHUB_OUTPUT
          echo "created=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"
      - name: Prep npm for using packages from buf.build
        run: |
          pnpm config set @buf:registry  https://buf.build/gen/npm/v1/

      - name: Install dependencies
        run: pnpm install
      - name: Test
        run: pnpm test:no-watch --passWithNoTests
        env:
          CI: true
          RUN_SLOW_TESTS: true
      - name: Build
        run: pnpm build
        env:
          CI: false
      - name: Copy to docker
        run: cp -r dist/ docker/dist

      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: docker
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.prep.outputs.tags }}
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.version=${{ steps.prep.outputs.version }}
            org.opencontainers.image.description=iRacelog frontend

      - uses: release-drafter/release-drafter@v6
        id: rd
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: prepare changlog
        run: |
          echo "${{ steps.rd.outputs.body }}" > "${{ runner.temp }}/CHANGELOG.md"

      - name: Build release (on tags)
        run: |
          PRE_RELEASE=
          if ! [[ ${{ github.event.ref }} =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              PRE_RELEASE=--prerelease
          fi

          gh release create ${{ steps.prep.outputs.version }} $PRE_RELEASE -F "${{ runner.temp }}/CHANGELOG.md"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.ref_type == 'tag'
